name: test-schell-script
on: [push]
jobs:
  check-bash-version:
    runs-on: ubuntu-lastest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: action
        run: echo "first action!"

